import fs from "fs";
import path from "path";
// import { Kol } from "../payload/kolektoj/nomoj";

const kapMesagxo = /*ts*/ `
/* tslint:disable */
/* eslint-disable */
/**
 * This file is automatically generated.
 * If you need to modify these types, please modify the script that generates them,
 * And rerun the script \`yarn generate:types\` to regenerate this file.
 */
`.trim();

const enportoj = `
import { Subtrahi } from './utiltipoj';
`.trim();

/** Helper types derived from the asserted types */
const ekstrajTipoj = `
export type Rolo = NonNullable<Uzanto<0>["roloj"]>[number];
export type Signifo = NonNullable<Termino<0>["signifoj"]>[number];
export type SignifoEkzemplo = NonNullable<Signifo["ekzemploj"]>[number];
export type SignifoSinonimo = NonNullable<Signifo["sinonimoj"]>[number];
export type Tradukoj = NonNullable<Termino<0>["lingvoj"]>;
`;

const asertitajTipojDosiernomo = "payload-asertitaj-tipoj.ts";
const tipujo = path.resolve(__dirname, "../tipoj");
const eligvojo = path.resolve(tipujo, asertitajTipojDosiernomo);

// const kolektoj = Object.values(Kol);

try {
  const vaniltipoj = fs.readFileSync(`${tipujo}/payload-tipoj.ts`, "utf-8");
  const gxisdatigitajTipoj = vaniltipoj
    .replace(/\/\*[^]+\*\/\r?\n\r?\n/g, "") // Forigi komencan ts-lint komenton
    .replace(/^export interface (\w+)/gm, "export interface $1<Profundo extends number = 2>") // Konverti interfacojn en tipojn
    .replace(/^}$/gm, "};") // Doni punktokomon al fino de tipo
    .replace(/: string \| ([A-Z]\w+);/g, ": Profundo extends 0 ? string : $1<Subtrahi<Profundo>>;")
    .replace(/: \(string \| null\) \| ([A-Z]\w+);/g, ": (Profundo extends 0 ? string : $1<Subtrahi<Profundo>>) | null;")
    .replace(/: string \| ([A-Z]\w+) \| null;/g, ": (Profundo extends 0 ? string : $1<Subtrahi<Profundo>>) | null;")
    .replace(/: \(string \| ([A-Z]\w+)\)\[\];/g, ": Profundo extends 0 ? string[] : $1<Subtrahi<Profundo>>[];")
    .replace(/: \(string \| ([A-Z]\w+)\)\[\] \| null;/g, ": (Profundo extends 0 ? string[] : $1<Subtrahi<Profundo>>[]) | null;")
    // .replace(new RegExp(`^(\\s{4}(?:${kolektoj.join("|")}): [A-Z]\\w+);`, "gm"), "$1<Profundo>;") // Aldoni ĝeneralilon Profundo al la kolekto Config
    .replace(/declare module 'payload'[^]*/m, "/* Derivitaj tipoj */");

  const asertitajTipoj = `${kapMesagxo}\n\n${enportoj}\n\n${gxisdatigitajTipoj}${ekstrajTipoj}`;
  fs.writeFileSync(eligvojo, asertitajTipoj);
  console.info(`✨ Asertitaj tipoj generitaj en ${eligvojo}`);
} catch (e) {
  console.error(`💥 Eraro dum asertitaj tipoj kreatis!`);
  console.error(e);
}
