/* tslint:disable */
/* eslint-disable */
/**
 * This file is automatically generated.
 * If you need to modify these types, please modify the script that generates them,
 * And rerun the script `yarn generate:types` to regenerate this file.
 */

import { Subtrahi } from './utiltipoj';

export interface Config {
  collections: {
    categories: Category;
    uzantoj: Uzantoj;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
};
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category<Profundo extends number = 2> {
  id: string;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
};
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uzantoj".
 */
export interface Uzantoj<Profundo extends number = 2> {
  id: string;
  name?: string | null;
  roles?: ('admin' | 'user')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
};
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference<Profundo extends number = 2> {
  id: string;
  user: {
    relationTo: 'uzantoj';
    value: Profundo extends 0 ? string : Uzantoj<Subtrahi<Profundo>>;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
};
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration<Profundo extends number = 2> {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
};


/* Derivated types */
