/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    uzantoj: Uzanto;
    terminoj: Termino;
    notoj: Noto;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uzantoj".
 */
export interface Uzanto {
  id: string;
  nomo?: string | null;
  roloj?: ('admin' | 'vortaristo')[] | null;
  kreinto?: (string | null) | Uzanto;
  gxisdatiginto?: (string | null) | Uzanto;
  createdAt: string;
  updatedAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terminoj".
 */
export interface Termino {
  id: string;
  termino: string;
  signifoj: {
    signifo: string;
    ekzemploj?:
      | {
          ekzemplo?: string | null;
          id?: string | null;
        }[]
      | null;
    sinonimoj?:
      | {
          sinonimo?: string | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  notoj?: (string | Noto)[] | null;
  lingvoj?: {
    de?:
      | {
          traduko: string;
          id?: string | null;
        }[]
      | null;
    en?:
      | {
          traduko: string;
          id?: string | null;
        }[]
      | null;
    es?:
      | {
          traduko: string;
          id?: string | null;
        }[]
      | null;
    fr?:
      | {
          traduko: string;
          id?: string | null;
        }[]
      | null;
    ja?:
      | {
          traduko: string;
          id?: string | null;
        }[]
      | null;
    pt?:
      | {
          traduko: string;
          id?: string | null;
        }[]
      | null;
    zh?:
      | {
          traduko: string;
          id?: string | null;
        }[]
      | null;
  };
  kreinto?: (string | null) | Uzanto;
  gxisdatiginto?: (string | null) | Uzanto;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notoj".
 */
export interface Noto {
  id: string;
  simbolo: string;
  signifo?: string | null;
  kreinto?: (string | null) | Uzanto;
  gxisdatiginto?: (string | null) | Uzanto;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'uzantoj';
    value: string | Uzanto;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}